### ISSUE TITLE
Vignette on hover

### ISSUE THREAD

**Issue by ItzSylex** [x6r/dracula#11]
Hey, so I am trying to figure out if its possible to disable a vignette that shows up whenever u hover over the screenshare section of a call

Here's what im talking about

This is without hovering
![unknown](https://user-images.githubusercontent.com/42503343/132060785-c6dd4be9-8693-4eca-bbaf-bac216de5d65.png)

And this with hover

![unknown (1)](https://user-images.githubusercontent.com/42503343/132060829-23f55ef2-eecb-40ec-9115-64a75d030d0c.png)

This looks like a box-shadow, not sure if theres a way to remove it or change the color, if so, please let me know

**Comment by slowstab** [comment]
that's comes from discord. it's black by default so theme changes its color to match the background color, except it doesn't look like the background color is correct in your screenshots. if i'm looking at the right thing this is what it should look like (with hover):
![scrot](https://user-images.githubusercontent.com/36301891/132064135-733cf07c-bd14-45e2-8689-a9f139ddfc3d.png)
are you using a different theme with dracula maybe?

if you want to remove the vintage you can either: 
1. put `.gradientContainer-10lXLB {background: transparent !important;}` in the quick/custom css section of your client mod
2. replace [line 776 to line 792](https://github.com/slowstab/dracula/blob/db7f1bf10524b51c6b83d3240f052415222ccb75/dracula.scss#L776-L792) with the code snippet above if you want to use your own fork

if you want to change its color either:
1. copy the same lines, change the initial 3 values of each line prefixed with 'rgba' to whichever rgb color you want, and paste it in quick/custom css
2. directly replace the colors in the theme file if you want to use your fork

**Comment by ItzSylex** [comment]
Thanks for the quick reply `.gradientContainer-10lXLB {background: transparent !important;}` is exactly what I was looking for, thanks!

**Comment by ItzSylex** [comment]
Looks like the vignette also shows up in the video reproducer

![image](https://user-images.githubusercontent.com/42503343/132141667-881437be-29c3-4997-acd9-dc920fd562d1.png)

How would you go about turning it off there as well?

**Comment by x6r** [comment]
`.metadata-13NcHb {background: transparent !important;}`
same as above

**Comment by ItzSylex** [comment]
Thanks again 🎉
