### ISSUE TITLE
Theme doesn't work

### ISSUE THREAD

**Issue by lex1k1337** [x6r/dracula#12]
![image](https://user-images.githubusercontent.com/54908019/132131253-eaa84865-14ee-4344-9c08-a41c8d55472f.png)
I don't know why, but i guess. The main link for theme (https://slowstab.github.io/dracula/BetterDiscord/source.css) was deleted. So how soon you will fix it?

**Comment by x6r** [comment]
im aware, already fixed restart your client

**Comment by lex1k1337** [comment]
Thanks a lot <3
