### ISSUE TITLE
Add color for pronouns db plugin

### ISSUE THREAD

**Issue by Slimakoi** [x6r/dracula#14]
Add the main color (`var(--dracula-accent)`) to the pronouns db plugin class

Class
`.PronounDB-style-container .PronounDB-style-header`

Example Image 
![Screenshot 2021-11-14 171556](https://user-images.githubusercontent.com/24621566/141691255-46731728-766b-4d24-9f5a-c9fe3df20308.png)

**Comment by x6r** [comment]
they are already colored for me without adding anything both in the user and the profile modal

can you show a full screenshot so it is clear where it is, without other css additions?

**Comment by Slimakoi** [comment]
Here is the screenshot without custom css
![Screenshot 2021-11-14 171556](https://user-images.githubusercontent.com/24621566/141693379-c275dcb0-1d88-48f7-bdc8-f29f2c95d848.png)
